#!/usr/bin/env python3
from __future__ import annotations

import json
import shutil
from pathlib import Path
from typing import Any
from urllib.parse import urlparse

ROOT = Path(__file__).resolve().parents[1]
CONFIGS = ROOT / "configs"
DOCS = ROOT / "docs"
RULES = CONFIGS / "mcp-skill-rules.json"


def load_json(path: Path) -> dict[str, Any]:
    if not path.exists():
        return {}
    return json.loads(path.read_text(encoding="utf-8"))


def configured_names() -> set[str]:
    names: set[str] = set()
    for path in sorted(CONFIGS.glob("*.sanitized.json")):
        data = load_json(path)
        servers = data.get("servers", {})
        if isinstance(servers, dict):
            names.update(servers.keys())
    return names


def display_bool(value: bool) -> str:
    return "yes" if value else "no"


def url_ok(url: str) -> bool:
    parsed = urlparse(url)
    return parsed.scheme in {"http", "https"} and bool(parsed.netloc)


def binary_status(rule: dict[str, Any]) -> tuple[str, str]:
    health_command = str(rule.get("health_command", "")).strip()
    expected_type = str(rule.get("expected_type", "")).strip()
    if expected_type == "hosted":
        url = str(rule.get("source_url", "")).strip()
        return ("url ok" if url_ok(url) else "url missing", "hosted URL format only")
    if not health_command:
        return "-", "no health_command"
    binary = health_command.split()[0]
    return (display_bool(shutil.which(binary) is not None), f"`{health_command}`")


def main() -> None:
    DOCS.mkdir(parents=True, exist_ok=True)
    rules = load_json(RULES)
    configured = configured_names()

    lines = [
        "# MCP Health",
        "",
        "Generated by `scripts/check-mcp-health.py`.",
        "Hosted MCPs validate URL shape only; this script does not perform network checks.",
        "",
        "| MCP | Configured | Binary exists | Source link | Related skills | Notes |",
        "| --- | --- | --- | --- | ---: | --- |",
    ]

    for name in sorted(rules.keys(), key=str.lower):
        rule = rules.get(name, {})
        if not isinstance(rule, dict):
            rule = {}
        skills = rule.get("include_skills", [])
        prefixes = rule.get("include_skill_prefixes", [])
        related_count = len(skills if isinstance(skills, list) else []) + len(prefixes if isinstance(prefixes, list) else [])
        source_url = str(rule.get("source_url", "")).strip()
        source = f"[link]({source_url})" if source_url else "-"
        binary, note = binary_status(rule)
        lines.append(
            f"| `{name}` | {display_bool(name in configured)} | {binary} | {source} | {related_count} | {note} |"
        )

    (DOCS / "health.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("wrote docs/health.md")


if __name__ == "__main__":
    main()
