#!/usr/bin/env python3
from __future__ import annotations

import json
import re
import tomllib
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
CONFIGS = ROOT / "configs"
DOCS = ROOT / "docs"

SOURCES = [
    ("codex", Path.home() / ".codex" / "config.toml", "mcp_servers"),
    ("claude", Path.home() / ".claude" / "settings.json", "mcpServers"),
    ("vscode", Path.home() / ".config" / "Code" / "User" / "mcp.json", "servers"),
]

SECRET_KEY_RE = re.compile(r"(secret|token|password|passwd|api[_-]?key|access[_-]?key|private[_-]?key|client[_-]?secret|consumer[_-]?secret|authorization|bearer)", re.I)
SECRET_VALUE_RE = re.compile(r"^(sk-|pk_|ghp_|github_pat_|xox[baprs]-|ck_|cs_|eyJ|AKIA|ASIA)")
URL_SECRET_RE = re.compile(r"([?&](?:key|token|secret|password|consumer_key|consumer_secret)=)[^&\s]+", re.I)


def load_config(path: Path) -> dict[str, Any]:
    if not path.exists():
        return {}
    text = path.read_text(encoding="utf-8")
    if path.suffix == ".toml":
        return tomllib.loads(text)
    return json.loads(text)


def redact_string(value: str) -> str:
    value = URL_SECRET_RE.sub(r"\1<redacted>", value)
    if SECRET_VALUE_RE.search(value):
        return "<redacted>"
    return value


def sanitize(value: Any, key: str = "") -> Any:
    if SECRET_KEY_RE.search(key):
        if isinstance(value, dict):
            return {k: "<redacted>" for k in value.keys()}
        if isinstance(value, list):
            return ["<redacted>" for _ in value]
        return "<redacted>"

    if key == "env" and isinstance(value, dict):
        return {k: "<redacted>" for k in sorted(value.keys())}

    if isinstance(value, dict):
        return {k: sanitize(v, k) for k, v in sorted(value.items())}
    if isinstance(value, list):
        return [sanitize(v, key) for v in value]
    if isinstance(value, str):
        if key == "args" and SECRET_KEY_RE.search(value):
            return "<redacted secret-loading argument>"
        return redact_string(value)
    return value


def server_summary(name: str, cfg: dict[str, Any]) -> dict[str, Any]:
    command = cfg.get("command") or cfg.get("type") or cfg.get("url") or ""
    args = cfg.get("args") if isinstance(cfg.get("args"), list) else []
    env = cfg.get("env") if isinstance(cfg.get("env"), dict) else {}
    return {
        "name": name,
        "command_or_type": sanitize(command),
        "arg_count": len(args),
        "env_keys": sorted(env.keys()),
    }


def main() -> None:
    CONFIGS.mkdir(parents=True, exist_ok=True)
    DOCS.mkdir(parents=True, exist_ok=True)

    inventory: list[tuple[str, Path, str, list[dict[str, Any]]]] = []

    for source, path, key in SOURCES:
        data = load_config(path)
        servers = data.get(key, {}) if isinstance(data, dict) else {}
        if not isinstance(servers, dict):
            servers = {}

        sanitized = {
            "source": source,
            "source_path": str(path),
            "server_key": key,
            "servers": sanitize(servers),
        }
        (CONFIGS / f"{source}.sanitized.json").write_text(
            json.dumps(sanitized, indent=2, sort_keys=True) + "\n",
            encoding="utf-8",
        )

        summaries = [server_summary(name, cfg if isinstance(cfg, dict) else {}) for name, cfg in sorted(servers.items())]
        inventory.append((source, path, key, summaries))

    lines = ["# MCP Inventory", "", "Generated by `scripts/snapshot-mcps.py`.", ""]
    for source, path, key, summaries in inventory:
        lines.extend([f"## {source}", "", f"Source: `{path}`", f"Server key: `{key}`", ""])
        if not summaries:
            lines.extend(["No MCP servers found.", ""])
            continue
        lines.append("| Server | Command/type | Args | Env keys |")
        lines.append("| --- | --- | ---: | --- |")
        for item in summaries:
            env_keys = ", ".join(f"`{k}`" for k in item["env_keys"]) or "-"
            lines.append(f"| `{item['name']}` | `{item['command_or_type']}` | {item['arg_count']} | {env_keys} |")
        lines.append("")

    (DOCS / "inventory.md").write_text("\n".join(lines), encoding="utf-8")
    print("wrote configs and docs/inventory.md")


if __name__ == "__main__":
    main()
